names = [
    'TshirtNo',
    'TshirtYes',
    'TshirtAmbiguous',
    'BackpackNo',
    'BackpackYes',
    'BackpackAmbiguous',
    'MaleNo',
    'MaleYes',
    'MaleAmbiguous',
    'CarryingNo',
    'CarryingYes',
    'CarryingAmbiguous',
    'LongHairNo',
    'LongHairYes',
    'LongHairAmbiguous',
    'LongJeansNo',
    'LongJeansYes',
    'LongJeansAmbiguous',
    'LongPantsNo',
    'LongPantsYes',
    'LongPantsAmbiguous',
    'MidShortPantsNo',
    'MidShortPantsYes',
    'MidShortPantsAmbiguous',
    'ShirtNo',
    'ShirtYes',
    'ShirtAmbiguous',
    'ShoulderBagNo',
    'ShoulderBagYes',
    'ShoulderBagAmbiguous',
    'SkirtNo',
    'SkirtYes',
    'SkirtAmbiguous',
    'UpperBodyBlack',
    'UpperBodyWhite',
    'UpperBodyGray',
    'UpperBodyRed',
    'UpperBodyGreen',
    'UpperBodyBlue',
    'UpperBodyUndefined',
    'UpperBodyAmbiguous',
    'UpperBodyOccluded',
    'LowerBodyBlack',
    'LowerBodyWhite',
    'LowerBodyKhaki',
    'LowerBodyGray',
    'LowerBodyBlue',
    'LowerBodyUndefined',
    'LowerBodyAmbiguous',
    'LowerBodyOccluded'
]

unival = [
    [
        'TshirtNo',
        'TshirtYes',
        'TshirtAmbiguous'
    ],
    [
        'BackpackNo',
        'BackpackYes',
        'BackpackAmbiguous'
    ],
    [
        'MaleNo',
        'MaleYes',
        'MaleAmbiguous'
    ],
    [
        'CarryingNo',
        'CarryingYes',
        'CarryingAmbiguous'
    ],
    [
        'LongHairNo',
        'LongHairYes',
        'LongHairAmbiguous'
    ],
    [
        'LongJeansNo',
        'LongJeansYes',
        'LongJeansAmbiguous'
    ],
    [
        'LongPantsNo',
        'LongPantsYes',
        'LongPantsAmbiguous'
    ],
    [
        'MidShortPantsNo',
        'MidShortPantsYes',
        'MidShortPantsAmbiguous'
    ],
    [
        'ShirtNo',
        'ShirtYes',
        'ShirtAmbiguous'
    ],
    [
        'ShoulderBagNo',
        'ShoulderBagYes',
        'ShoulderBagAmbiguous'
    ],
    [
        'SkirtNo',
        'SkirtYes',
        'SkirtAmbiguous'
    ],
    [
        'UpperBodyBlack',
        'UpperBodyWhite',
        'UpperBodyGray',
        'UpperBodyRed',
        'UpperBodyGreen',
        'UpperBodyBlue',
        'UpperBodyUndefined',
        'UpperBodyAmbiguous',
        'UpperBodyOccluded'
    ],
    [
        'LowerBodyBlack',
        'LowerBodyWhite',
        'LowerBodyKhaki',
        'LowerBodyGray',
        'LowerBodyBlue',
        'LowerBodyUndefined',
        'LowerBodyAmbiguous',
        'LowerBodyOccluded'
    ]
]

unival_titles = [
    'T-Shirt',
    'Backpack',
    'Male',
    'Carrying',
    'LongHair',
    'LongJeans',
    'LongPants',
    'MidShortPants',
    'Shirt',
    'Shoulder',
    'Skirt',
    'UpperBody',
    'LowerBody'
]

multival = [
]

multival_titles = [
]
